.env.example, docker-compose.yml
Docker Compose adds prefixes to services scoped by project. And thanks to importmaps, we no longer have to orchestrate separate processes for development or production! Thus, raw `rails s` works fine.
=> Remove redundant Docker Compose prefixes and reflect ability to run `rails s`

config/application.rb
This can differ for between developers, so it makes sense for more configurable options to utilize environment variables.
=> Allow for a HOST env var

.github/dependabot.yml
This spaces things out between runs on other repos.
=> Run Dependabot on Monday instead of Wednesday

app/controllers/application_controller.rb, app/controllers/concerns/authenticate.rb, app/controllers/concerns/set_current_request_details.rb, app/controllers/hackathons_controller.rb, app/controllers/users/authentications_controller.rb, app/controllers/users/sessions_controller.rb, app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/models/concerns/deliverable.rb, app/models/concerns/suppressible.rb, app/models/current.rb, app/models/event.rb, app/models/event/request.rb, app/models/event/requested.rb, app/models/user.rb, app/models/user/authenticatable.rb, app/models/user/authentication.rb, app/models/user/named.rb, app/models/user/session.rb, app/views/layouts/application.html.erb, app/views/user_mailer/authentication.html.erb, app/views/user_mailer/authentication.text.erb, app/views/users/authentications/new.html.erb, config/routes.rb, db/migrate/20230718223502_create_user_sessions.rb, db/migrate/20230718223503_create_event_requests.rb, db/schema.rb, test/application_system_test_case.rb, test/system/authentication_flow_test.rb
- When a `User` requests a sign in link with their email, an `Authentication` is created.
- An `Authentication` is `Deliverable`, through it's `delivery`, a mailer. (we create a global concern to utilize this common abstraction in the future).
- An `Authentication` `has_secure_token`, which is a part of the link that gets sent.
- When a valid `Authentication#complete`s, its newly-created `Session` `has_secure_token` that gets stored in an encrypted cookie.
- When a request comes in, the controller(s) `Authenticate` it by querying `Session`s with the token.
- The `Current.request_id`, `user_agent`, and `ip_address` get saved every time there's an `Event` with those details.
This was inspired by [DHH's video on concerns](https://youtu.be/M3JPTOTqsnE?t=1139) and [ActiveRecord's …
=> Implement authentication

config/environments/test.rb
```
/Users/garyhtou/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/spring-4.1.1/lib/spring/application.rb:100:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
```
https://github.com/rails/spring/issues/598#issuecomment-1268885973
=> Change config to allow for Spring in test environment

app/models/hackathon.rb, app/models/hackathon/applicant.rb, db/migrate/20230718235719_add_applicant_to_hackathons.rb, db/schema.rb, test/fixtures/hackathons.yml, test/fixtures/users.yml, test/models/hackathon/regional_test.rb, test/models/hackathon_test.rb
The main reason is to just have an `email` associated with a Hackathon
=> Add Applicant to Hackathons

.github/workflows/ci.yml
It takes around 10 seconds for Postgres to boot up, and the current buffer between when it's initialized and when it has to be ready is 30+ seconds, so we should be fine to shave off the time, but we can always add it back in if necessary.
=> Don't wait for PG to be ready to progress in GH CI

app/controllers/api/concerns/errors.rb, app/errors/api/bad_request_error.rb, app/errors/api/error.rb, app/errors/api/invalid_api_version_error.rb, app/errors/api/not_found_error.rb
This helps ensure uniform `type`s and `title`s when reusing these errors elsewhere.
=> API: error classes for NotFound and InvalidApiVersion

app/models/hackathon/digest.rb, app/models/hackathon/digest/listing.rb, app/models/hackathon/digest/listings.rb, app/models/hackathon/digest/listings/by_location.rb, app/models/hackathon/regional.rb, app/models/hackathon/scheduled.rb, app/models/hackathon/subscription.rb, app/models/hackathon/subscription/regional.rb, app/models/location.rb, app/models/user.rb, db/migrate/20230726064503_add_belongs_to_subscription_on_hackathon_digest_lisings.rb, db/schema.rb, test/fixtures/hackathons.yml, test/models/hackathon/digest/listings/by_location_test.rb, test/models/hackathon/regional_test.rb, test/models/hackathon/subscription_test.rb, test/models/location_test.rb
This PR contains working logic for building Digest Listings. Here's a very rough run down on how it works:
- If a Hackathon's location exactly matches a Subscription's location, it is included.
- Subscriptions that have a "significant component" of `city` will use coordinate distance. Anything within 150 miles will be included
- "significant component" is similar to the concept of sig figs in math
- See the `Location` PORO model for more info.
=> Digest Listing: Logic for searching nearby hackathons

app/models/hackathon/digest/listings/criterion/location.rb, app/models/location.rb, app/views/hackathons/digest_mailer/_subscription.html.erb, app/views/hackathons/digest_mailer/_subscription.text.erb, test/models/location_test.rb
Also, the Hackathon Digest mailer now says "_In_ country", rather than "_Near_ country". It'll still say "Near" for cities, but use "In" for states and countries.
=> Refactor and clean up `Location`

app/models/hackathon/digest/listings/criterion/location.rb, app/models/location.rb, test/models/hackathon/digest/listings/criterion/location_test.rb, test/models/location_test.rb
Fix a bug on filtering out overlapping subscriptions and add tests.
Previously, `US covers? Washington, US` would be false 🥲
=> Fix bug on filter overlapping subscriptions

app/mailers/user_mailer.rb
Under heavy job loads, this prioritizes sending user login emails
Ideally, I think we should be doing `deliver_now` rather than `deliver_later` for user logins
=> Set UserMailer queue to `critical`

app/controllers/concerns/authenticate.rb, app/controllers/users/sessions_controller.rb, db/migrate/20230815053636_make_auth_tokens_unique.rb, db/schema.rb, lib/constraints/admin.rb
No need for encryption when it's already a secure token, and it could help with debugging. We don't have production sessions at this point so it won't have any impact.
=> Make auth tokens unique and session tokens signed

config/initializers/console1984.rb
> If true, the console will ask for a username if it is empty. If false, it will raise an error if no username is set. Defaults to false.
https://github.com/basecamp/console1984#configuration
=> Console1984: Ask for username (don't raise error)

Gemfile, Gemfile.lock, config/environments/production.rb
Also provides LOGFMT for AppSignal's log attributes
https://docs.appsignal.com/logging/platforms/integrations/ruby.html#lograge
=> Install `lograge` to minimize log verbosity

README.md, app/models/concerns/deliverable.rb, app/models/user/authentication.rb
User auth mailers are critical and should not depend on having the background job server (Sidekiq) running
---
Also removes the `Deliverable#deliver_later` and `Deliverable#deliver_now` methods since they realistically will only be used by the callback and clutter the namespace
=> Deliver user auth mailers now (rather than later)

app/helpers/mailer_helper.rb
`@_message.to` could also be a string! who knew 👀
=> Patch bug with `MailerHelper.recipient_name`

app/jobs/hackathons/config/sidekiq.yml
Since we're still using Sidekiq in prod, we should bring back the config so that Sidekiq is aware of the `critical` and `low` queues (by default, it only knows the `default` queue)
https://github.com/sidekiq/sidekiq/wiki/Advanced-Options
The file was removed in https://github.com/hackclub/hackathons-backend/pull/150
=> Bring back sidekiq config

app/models/concerns/taggable.rb
It'll return the new taggings if all tags were applied. Otherwise, it'll return false to indicate that at least one tag does not exist.
=> Make `tag_with` return something useful

Gemfile.lock
Reverts hackclub/hackathons-backend#182
This update broke deploys
=> Revert "Bump rails from `c0980d3` to `ccee593`"

app/assets/stylesheets/components/_hackathon.scss, app/views/admin/hackathons/_snippet.html.erb, app/views/admin/hackathons/index.html.erb, app/views/layouts/admin.html.erb
https://github.com/hackclub/hackathons-backend/assets/20099646/98d40944-97ea-4a4e-8de0-e35244f6d8b8
<sup>_the 3rd and 4th hackathons' logos aren't rendering properly. probably due to invalid formats_</sup>
=> Style admin hackathons index

app/mailers/hackathons/digest_mailer.rb, test/mailers/previews/hackathon/digest_mailer_preview.rb
For important pieces of code (especially when notifying users), I'd rather be more explicit and remove assumptions. Rather than defaulting to digests sent in the past 6 days, we should require them to be passed in.
```ruby
digests = Hackathon::Digest.where(created_at: 6.days.ago...Time.now)
Hackathons::DigestMailer.admin_summary(digests).deliver_later
```
This helps prevent assumptions that may not hold true in future code changes.
=> DigestMailer#admin_summary: Remove unused code

.github/workflows/ci.yml
Now if tests hang, it won't go on for way longer.
=> Add 15-minute timeout for testing

db/schema.rb
This likely got out of order due to merge conflicts.
@northeastprince if you're seeing this same change when running `bin/rails db:migrate` on `main`, then please go ahead and merge it!
=> Rails schema autoformatting

config/environments/production.rb
Lograge is great for most cases, but there are times when you might want more information - this sends lograge output to AppSignal but keeps the default, more detailed logging to `$stdout` that can be `grep`'d via `kamal app logs -g <request_id>`.
=> Just send lograge output to AppSignal

app/controllers/admin/hackathons/names_controller.rb
The hackathon attribute editing forms for admins just use the general hackathon update action, which works fine.
=> Remove unused hackathon name update action

app/views/admin/hackathons/show.html.erb
An explicit hold's purpose is to just mark that someone is on it, but waiting for something (clarification, edit, etc.), so we shouldn't require it to change a decision.
=> Don't require holding for review to approve/reject

Gemfile.lock
The AppSignal Ruby gem has better support for Rails 7.1 and higher with the latest patch release. Update the gem to see event timeline reporting and group breakdowns.
=> Fix Rails >= 7.1 reporting by updating AppSignal

app/views/hackathons/submissions/_form.html.erb
We don't have logic to handle different time zones, and don't really need to as long as reviewers are aware times are submitted in UTC. We do, however, use [local_time](https://github.com/basecamp/local_time) to render most timestamps in the time zone of client devices.
=> Ask for UTC times (not local times) from applicants

app/views/admin/header/_nav.html.erb
It's not part of the admin panel, so it makes more sense to keep the admin panel open.
=> Open admin panel's new submission link in a new tab

app/models/hackathon/website.rb, app/models/hackathon/website/archivable.rb
#318 was caused by a hackathon being submitted with an invalid (unreachable) site. This shouldn't have been possible, since `Hackathon#eligible_for_archive?` checks if the website is marked as up, and the `ArchiveWebsiteJob` only archives the website if that conditional is met. However, we're also attempting to archive the site right after creation which bypasses the check (which would've passed anyway since the daily `RefreshWebsiteStatusesJob` wouldn't have processed the site yet.
=> Handle archive attempts for unresponsive websites

app/controllers/concerns/authenticate.rb, app/controllers/users/sessions_controller.rb
This makes it so the cookie is only sent over HTTPS.
=> Set session_token cookies as Secure in production

config/deploy.yml, config/initializers/yjit.rb
There wasn't a notable decrease in response times with YJIT, and this way we're able to process more requests at once again.
=> Disable YJIT and return to 2 web processes

Gemfile.lock
=> Revert Rails update from `299900f` to `2c5fe6f`

app/models/hackathon/digest/listings/criterion/location.rb
This avoids a redundant geocoding lookup, which should speed digest deliveries up by a lot.
=> Use direct coordinates for subscription location nearby lookups

app/views/hackathons/submissions/_form.html.erb
Goals:
- We want organizers to understand that we're NOT shipping a box of stickers for all attendees to share. This is just a couple of stickers for the organizer
- Stickers will only be sent when their hackathon is approved for listing. A rejection means no stickers
- I'm not confident we include postcards in the envelopes — so I'm removing them from the copy
=> Minor copy edit for swag form question
