hackclub/hackathons-backend

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/routes.rb
http://localhost:3000/letter_opener
> Add LetterOpenerWeb for development mailer delivery

- Gemfile
- Gemfile.lock
- app/models/hackathon.rb
- app/models/hackathon/swag.rb
- app/models/mailing_address.rb
- db/migrate/20230720000103_create_mailing_addresses.rb
- db/schema.rb
- test/fixtures/mailing_addresses.yml
- test/models/hackathon_test.rb
- test/models/mailing_address_test.rb
The `MailingAddress` model does not support geocoding as it's not necessary!
> Create MailingAddress for Hackathon swag shipment

- app/controllers/api/concerns/errors.rb
- app/controllers/api/subscriptions_controller.rb
- app/controllers/api_controller.rb
- app/helpers/api_helper.rb
- app/views/api/subscriptions/_subscription.json.jbuilder
- app/views/api/users/_user.json.jbuilder
- config/routes.rb
It's as simple as POSTing to `/api/v1/subscription` with an `email` and `location` in the JSON body!
Upon a successful request, it will return the subscription object as JSON.
<table>
<tr>
<td>Request
<td>Response
<tr>
<td>
`POST` to `/api/v1/subscription`
```json
{
"location": "seattle wa",
"email": "gary@hackclub.com"
}
```
<td>
```json
{
"id": "qYrIOk",
"type": "hackathon-subscription",
"status": "active",
"location": {
"city": "Seattle",
"province": "Washington",
"country_code": "US",
"postal_code": null
},
"subscriber": {
"id": "WPSav8MYM",
"type": "user",
"email_address": "gary@hackclub.com",
"created_at": "2023-07-25T08:57:46.151Z"
},
"created_at": "2023-07-25T08:57:46.862Z"
}
```
</table>
_from Strong Parameters_ 
<table>
<tr>
<td>Request
<td>Response
<tr>
<td>
`POST` to …
> API: create Subscription

- Gemfile
- Gemfile.lock
[Fixes #71 and redundant anyway!](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1641139415)
> Remove `webdrivers`

- app/models/hackathon/subscription/regional.rb
Previously, you could resubscribe to a Subscription and end up with duplicates
> Fix duplicate Subscription validation

- .env.example
- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- README.md
- app/models/hackathon/digest/listings.rb
- app/models/user.rb
- app/sidekiq/hackathon/digest_job.rb
- config/application.rb
- config/environments/production.rb
- config/routes.rb
- config/schedule.yml
- config/sidekiq.yml
- docker-compose.yml
- lib/constraints/admin.rb
- test/test_helper.rb
Sends a weekly digest to all users
closes https://github.com/hackclub/hackathons-backend/issues/84
> Install Sidekiq and Redis + Weekly Hackathon Digest Job

- app/mailers/hackathons/digest_mailer.rb
- app/models/hackathon/subscription/regional.rb
- app/models/user/privileged.rb
- app/views/hackathons/digest_mailer/_hackathon.html.erb
- app/views/hackathons/digest_mailer/admin_summary.html.erb
- test/mailers/previews/hackathon/digest_mailer_preview.rb
- To: bank@hackclub.com
- CC: all admins
<br/>
<details>
<summary>The normal digest mailer ("Hackathons near you") remains the same, expect for some minor margin changes</summary>
</details>
Closes https://github.com/hackclub/hackathons-backend/issues/28
> Digest: Admin Summary

- config/database.yml
See https://github.com/ged/ruby-pg/issues/311#issuecomment-561927000 for more details
> Fix Postgresql seg fault when running system tests

- app/controllers/api/stats/hackathons/subscriptions_controller.rb
- app/views/api/stats/hackathons/subscriptions/index.json.v1.jbuilder
- config/routes.rb
Replaces https://github.com/hackclub/hackathons/blob/1ad8ff8696cbdcacb4d04feb34084ec8f3cafdb8/lib/data.js#L71-L83
> API: Expose Subscription's distinct count of cities and countries

- app/helpers/api_helper.rb
- app/models/airtable/hackathon.rb
- app/models/airtable/subscriber.rb
- app/models/concerns/eventable.rb
- app/models/concerns/taggable.rb
- app/models/hackathon/brand.rb
- app/models/hackathon/gathering.rb
- app/models/hackathon/regional.rb
- app/models/hackathon/subscription/regional.rb
- app/models/mailing_address.rb
- db/migrate/20230815050917_add_airtable_id_to_hackathons.rb
- db/migrate/20230815052624_add_airtable_id_to_hackathon_subscriptions.rb
- db/schema.rb
- doc/airtable_data_migration.md
- lib/tasks/airtable_data.rake
- test/models/tagging_test.rb
It's gross, it's ugly, but it works! (and will only be used once-ish)
- A few of our validations only ran on `context: :submit`. I changed some of those so that they're always run, but allow for `nil`. And on `submit`, they would also validate presence.
- Geocoding for Subscriptions now bias the United States over other countries
Closes https://github.com/hackclub/hackathons-backend/issues/4
Closes https://github.com/hackclub/hackathons-backend/issues/27
> Airtable Migration Script

- app/controllers/concerns/authenticate.rb
- app/controllers/users/sessions_controller.rb
- lib/constraints/admin.rb
Even if we wanna add limits in the future, we should keep those in the application itself for flexibility.
> Don't expire `session_token`

- .github/workflows/cd.yml
Don't know what I was thinking with that...
> Fix cd.yml syntax from #117

- .github/workflows/cd.yml
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
> Use automatic token authentication for GHCR

- app/views/users/authentications/new.html.erb
> Sign in: Add link to letter opener when in development

- config/environments/production.rb
Images weren't loading in prod mailers
> Set asset host for production

- .env.example
- .github/workflows/cd.yml
- Gemfile
- Gemfile.lock
- README.md
- app/javascript/controllers/application.js
- app/javascript/controllers/appsignal.js
- config.ru
- config/appsignal.yml
- config/deploy.yml
- config/environment.rb
- config/environments/production.rb
- config/importmap.rb
`APPSIGNAL_PUSH_API_KEY` has been set on GitHub secrets
> Install AppSignal for monitoring, reporting, and logging

- app/mailers/application_mailer.rb
- app/views/layouts/mailer.html.erb
with
without
closes https://github.com/hackclub/hackathons-backend/issues/131
> Remove default unsubscribe links

- .github/workflows/ci.yml
Update Actions, reorder slightly
> Tidy up CI

- app/controllers/api/stats/hackathons_controller.rb
- app/views/api/stats/hackathons/index.json.v1.jbuilder
- config/routes.rb
closes https://github.com/hackclub/hackathons-backend/issues/153
> API: Add Hackathon pending count stat

- .github/workflows/cd.yml
- app/views/layouts/admin.html.erb
- app/views/layouts/application.html.erb
- config/deploy.yml
Closes https://github.com/hackclub/hackathons-backend/issues/151
> AppSignal: Move Front-end API Key to env var

- bin/console
We'll bug you until we get your name 🙂
> `bin/console`: Ask for console user until it's given

- app/views/hackathons/subscriptions/_manage.html.erb
- app/views/hackathons/subscriptions/index.html.erb
- app/views/hackathons/subscriptions/unsubscribe_all.html.erb
- app/views/layouts/application.html.erb
> Style unsubscribe pages

- app/assets/stylesheets/shared/_form.scss
- app/views/hackathons/submissions/_form.html.erb
- app/views/hackathons/submissions/new.html.erb
These are slightly opinionated changes but I added some extra styling that makes the form closer to other forms / sites we have... thoughts?
> Add Additional Styling To Form

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_hackathon.scss
- app/assets/stylesheets/components/_timeline.scss
- app/helpers/application_helper.rb
- app/models/event.rb
- app/views/admin/hackathons/show.html.erb
- app/views/events/_timeline.html.erb
also clean up some Hackathon show page css
> Style timeline

- app/assets/stylesheets/components/_hackathon.scss
- app/views/admin/hackathons/show.html.erb
> Make white transparent logos/banners visible

- app/views/hackathons/digest_mailer/_subscription.html.erb
- app/views/layouts/mailer.html.erb
I sent a test digest in prod and it showed up looking a little broken in Gmail. hopefully, this will fix it
testing using https://www.putsmail.com
> Fix up mailer

- config/environments/production.rb
> Don't log health checks

- .github/workflows/cd.yml
- .mrsk/hooks/post-deploy
- .mrsk/hooks/pre-connect
- Gemfile
- Gemfile.lock
- README.md
- bin/console
- config/deploy.yml
> MRSK -> Kamal (its new name)

- app/mailers/hackathon_mailer.rb
> Fix syntax for admin email address pluck

- .github/workflows/ci.yml
- test/application_system_test_case.rb
- test/test_helper.rb
Hopefully this will solve the extreme flakiness I've been seeing...
> Don't parallelize system tests

- app/models/user.rb
> Don't redundantly specify `foreign_key`s

- README.md
Reflects the possibility of dependency changes or updates, invalidating a big part of the Docker cache.
> Update approximate deploy time in README.md

- app/views/admin/header/_nav.html.erb
It's not part of it, so it doesn't belong there.
> Just remove the new submission link from the admin panel

- public/loaderio-e423fef5940eccd21632535cccb07276.txt
> Remove file for loader.io verification [skip ci]

- app/models/hackathon/website.rb
- lib/http_url_validator.rb
~~Stolen from~~ inspired by https://stackoverflow.com/a/7167988, closes #282.
> More comprehensive URL validation

- app/models/hackathon/scheduled.rb
> Allow historical hackathons to be submitted

- app/jobs/hackathons/website_status_refresh_job.rb
- app/jobs/hackathons/website_statuses_refresh_job.rb
Hopefully lessens these duration(s):
> Break out `WebsiteStatusesRefreshJob`

- config/initializers/sidekiq.rb
Will revert once hotwired/turbo-rails#522 is fixed.
> Disable Sidekiq strict args checking

- test/application_system_test_case.rb
Hopefully fixes some flaky system tests.
> Wait longer for element queries in system tests

- app/models/hackathon/branded.rb
- app/views/admin/hackathons/_snippet.html.erb
- app/views/admin/hackathons/show.html.erb
- app/views/hackathons/digest_mailer/_hackathon.html.erb
This also makes it so everyone sees the same dimensions across the admin panel and frontend.
> Use variants everywhere to cut back on file sizes

- Dockerfile
- app/controllers/database_dumps_controller.rb
- app/jobs/database_dump_job.rb
- app/models/database_dump.rb
- app/models/database_dump/processed.rb
- app/views/database_dumps/edit.html.erb
- app/views/database_dumps/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- db/migrate/20240107231455_create_database_dumps.rb
- db/schema.rb
This will allow for more realistic development and opportunities for others to create their own projects based off of hackathon data.
> Add public database dumps of the hackathons table

- Gemfile
- Gemfile.lock
- test/application_system_test_case.rb
- test/models/user_test.rb
- test/system/admin/users_test.rb
- test/system/hackathon_submission_test.rb
https://github.com/basecamp/audits1984/pull/52#issuecomment-1866299789
> Switch to Cuprite for system tests

- app/views/shared/_full_page_card.html.erb
> Remove duplicate footer on submission form

- app/views/admin/users/show.html.erb
> Require confirmation of user promotions and demotions

- Dockerfile
https://blog.appsignal.com/2021/09/21/how-to-reduce-memory-bloat-in-ruby.html
> Add jemalloc to optimize memory allocation

- app/models/hackathon/website/archivable.rb
- config/environments/test.rb
- test/models/tagging_test.rb
Also fixes a bug for hackathons with no websites.
> Don't archive hackathon websites right after creation or run jobs async in tests

- Gemfile
- Gemfile.lock
- app/models/hackathon/subscription/regional.rb
- config/initializers/geocoder.rb
We've been exceeding Nominatim's usage limits, so this will mitigate that.
> Use AWS for geocoding in production

- app/models/hackathon/regional.rb
https://hackclub.slack.com/archives/C06F779PJCT/p1717122121962439
> Make `street: nil`

- app/models/hackathon/digest.rb
https://dash.hackathons.hackclub.com/admin/audits/sessions/Q2xtzX
> Don't record many useless events for digests

- app/views/api/hackathons/_hackathon.json.v1.jbuilder
```
[{"id":"3y7I22","name":"RythmHacks","website":"1","start":"2024-09-01T18:00:00.000Z","end":"2024-09-03T11:00:00.000Z","createdAt":"2024-04-15T19:34:27.697Z","logo":"https://dash.hackathons.hackclub.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6Mzg0NiwicHVyIjoiYmxvYl9pZCJ9fQ==--64cd2da399b9dcbf07d84533fca93f273e5b06cd/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOlsxMjgsMTI4XX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--aed3fb345df101cd22ac6ef68ee4e4dbe8543f96/logo.451bfd9d6ab2062434dc.png","banner":"https://dash.hackathons.hackclub.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6Mzg0NywicHVyIjoiYmxvYl9pZCJ9fQ==--da52bc76b697f2a8e5296dcae9ed94025255fcf3/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOls …
```
> Attempt to fix hackathons.hackclub.com

- app/models/database_dump/processed.rb
> Ensure SQLite dumps are uploaded

- config/initializers/sidekiq.rb
Reverts hackclub/hackathons-backend#346
> Reenable Sidekiq strict args checking

- Gemfile.lock
Reverts #565 because of sidekiq-cron/sidekiq-cron#508
> Revert sidekiq update from 7.3.2 to 7.3.4

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/stylesheets/admin.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/index.scss
- app/assets/stylesheets/shared/_spacing.scss
- app/assets/stylesheets/shared/index.scss
- app/views/layouts/admin.html.erb
- config/application.rb
- config/initializers/assets.rb
- config/puma.rb
- lib/puma/plugin/dartsass.rb
rails/mission_control-jobs#177
> Switch to Dartsass to enable #568

- app/jobs/hackathons/website_archival_job.rb
- app/models/hackathon/website/archivable.rb
- lib/internet_archive/capture.rb
This ensures we'll never exceed the rate limit
> Extract website archival verification into separate job

- app/jobs/application_job.rb
- app/jobs/hackathons/website_archival_job.rb
- app/models/concerns/rate_limitable.rb
- app/models/hackathon/website/archivable.rb
- app/models/lock.rb
- config/initializers/action_mailer_concurrency.rb
- config/schedule.yml
- db/migrate/20250103164545_create_locks.rb
- db/schema.rb
For some reason this whole time I thought Solid Queue's concurrency controls did this... 🤦‍♂️
> Actually rate limit when needed
